# Generated by Django 5.1.2 on 2026-02-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="people",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
